name: Run CI

on: [push]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['8.1', '8.2']

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: cs2pr

      - name: Install dependencies
        run: composer install

      - name: Run phpcs
        run: ./vendor/bin/phpcs -q --report=checkstyle | cs2pr

      - name: Run Phpunit
        run: php -dzend.assertions=1 ./vendor/bin/phpunit

      - name: Run Qodana
        if: matrix.php-versions == '8.2'
        uses: JetBrains/qodana-action@v2022.3.4
