name: Run CI

on: [push]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['8.2']
        dependencies: ['normal', 'authoritative']

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: cs2pr

      - name: Install dependencies
        run: composer install

      - name: Run phpcs
        run: ./vendor/bin/phpcs -q --report=checkstyle | cs2pr

      - name: Run Phpunit
        run: php -dzend.assertions=1 ./vendor/bin/phpunit
